import 'package:eatwise/features/food_ai/domain/food_item.dart';

/// Curated local database of popular Philippine retail barcodes.
/// Provides instantaneous offline barcode resolution for common Filipino products.
class PhilippineBarcodeDatabase {
  PhilippineBarcodeDatabase._();

  static final Map<String, FoodItem> _products = {
    // ═══ COFFEE & BEVERAGES ═══
    '4800016644331': const FoodItem(
      name: 'Nescafe 3-in-1 Original',
      nameTagalog: 'Nescafe 3-in-1',
      portionSizeGrams: 20,
      portionDescription: '1 sachet (20g)',
      calories: 97,
      proteinG: 1.0,
      carbsG: 16.0,
      fatsG: 3.0,
      confidence: 1.0,
      reasoning: 'Local Barcode Database (Nescafe)',
    ),
    '4800016644348': const FoodItem(
      name: 'Nescafe Classic Instant Coffee',
      nameTagalog: 'Nescafe Classic',
      portionSizeGrams: 2,
      portionDescription: '1 mug (2g powder)',
      calories: 5,
      proteinG: 0.3,
      carbsG: 0.8,
      fatsG: 0.0,
      confidence: 1.0,
      reasoning: 'Local Barcode Database (Nescafe)',
    ),
    '4800092110011': const FoodItem(
      name: 'Kopiko Blanca 3-in-1 Coffee',
      nameTagalog: 'Kopiko Blanca',
      portionSizeGrams: 30,
      portionDescription: '1 sachet (30g)',
      calories: 140,
      proteinG: 1.0,
      carbsG: 23.0,
      fatsG: 5.0,
      confidence: 1.0,
      reasoning: 'Local Barcode Database (Kopiko)',
    ),
    '4800092110028': const FoodItem(
      name: 'Kopiko Brown Coffee Mix',
      nameTagalog: 'Kopiko Brown',
      portionSizeGrams: 26.5,
      portionDescription: '1 sachet (26.5g)',
      calories: 120,
      proteinG: 1.0,
      carbsG: 21.0,
      fatsG: 4.0,
      confidence: 1.0,
      reasoning: 'Local Barcode Database (Kopiko)',
    ),
    '4800092110035': const FoodItem(
      name: 'Kopiko Black 3-in-1 Coffee',
      nameTagalog: 'Kopiko Black',
      portionSizeGrams: 25,
      portionDescription: '1 sachet (25g)',
      calories: 110,
      proteinG: 0.8,
      carbsG: 22.0,
      fatsG: 2.0,
      confidence: 1.0,
      reasoning: 'Local Barcode Database (Kopiko)',
    ),
    '4800016055557': const FoodItem(
      name: 'Milo Activ-Go Chocolate Malt Drink',
      nameTagalog: 'Milo',
      portionSizeGrams: 22,
      portionDescription: '1 sachet (22g powder)',
      calories: 93,
      proteinG: 2.1,
      carbsG: 15.2,
      fatsG: 2.2,
      confidence: 1.0,
      reasoning: 'Local Barcode Database (Nestlé Milo)',
    ),
    '4800016054819': const FoodItem(
      name: 'Bear Brand Fortified Powdered Milk Drink',
      nameTagalog: 'Bear Brand Powdered',
      portionSizeGrams: 33,
      portionDescription: '1 glass (33g powder)',
      calories: 160,
      proteinG: 4.0,
      carbsG: 19.0,
      fatsG: 7.0,
      confidence: 1.0,
      reasoning: 'Local Barcode Database (Bear Brand)',
    ),
    '4800016054833': const FoodItem(
      name: 'Bear Brand Sterilized Milk',
      nameTagalog: 'Bear Brand Ready to Drink',
      portionSizeGrams: 200,
      portionDescription: '1 tetra pack (200ml)',
      calories: 140,
      proteinG: 5.0,
      carbsG: 16.0,
      fatsG: 6.0,
      confidence: 1.0,
      reasoning: 'Local Barcode Database (Bear Brand)',
    ),
    '4800552169005': const FoodItem(
      name: 'C2 Cool & Clean Green Tea (Apple)',
      nameTagalog: 'C2 Green Tea Apple',
      portionSizeGrams: 355,
      portionDescription: '1 bottle (355ml)',
      calories: 140,
      proteinG: 0.0,
      carbsG: 35.0,
      fatsG: 0.0,
      confidence: 1.0,
      reasoning: 'Local Barcode Database (Universal Robina)',
    ),
    '4800552169012': const FoodItem(
      name: 'C2 Cool & Clean Green Tea (Lemon)',
      nameTagalog: 'C2 Green Tea Lemon',
      portionSizeGrams: 355,
      portionDescription: '1 bottle (355ml)',
      calories: 140,
      proteinG: 0.0,
      carbsG: 35.0,
      fatsG: 0.0,
      confidence: 1.0,
      reasoning: 'Local Barcode Database (Universal Robina)',
    ),
    '4800361376823': const FoodItem(
      name: 'San Miguel Pale Pilsen',
      nameTagalog: 'San Miguel Pale Pilsen',
      portionSizeGrams: 330,
      portionDescription: '1 can (330ml)',
      calories: 135,
      proteinG: 1.2,
      carbsG: 10.5,
      fatsG: 0.0,
      confidence: 1.0,
      reasoning: 'Local Barcode Database (San Miguel Brewery)',
    ),
    '4800361376830': const FoodItem(
      name: 'San Mig Light',
      nameTagalog: 'San Mig Light',
      portionSizeGrams: 330,
      portionDescription: '1 can (330ml)',
      calories: 100,
      proteinG: 0.9,
      carbsG: 3.2,
      fatsG: 0.0,
      confidence: 1.0,
      reasoning: 'Local Barcode Database (San Miguel Brewery)',
    ),
    '4800361376847': const FoodItem(
      name: 'Red Horse Extra Strong Beer',
      nameTagalog: 'Red Horse Beer',
      portionSizeGrams: 330,
      portionDescription: '1 can (330ml)',
      calories: 175,
      proteinG: 1.5,
      carbsG: 14.0,
      fatsG: 0.0,
      confidence: 1.0,
      reasoning: 'Local Barcode Database (San Miguel Brewery)',
    ),

    // ═══ INSTANT NOODLES ═══
    '4801981110015': const FoodItem(
      name: 'Lucky Me! Instant Pancit Canton (Original)',
      nameTagalog: 'Lucky Me Pancit Canton Original',
      portionSizeGrams: 80,
      portionDescription: '1 pack (80g)',
      calories: 360,
      proteinG: 8.0,
      carbsG: 50.0,
      fatsG: 14.0,
      confidence: 1.0,
      reasoning: 'Local Barcode Database (Monde Nissin)',
    ),
    '4801981110022': const FoodItem(
      name: 'Lucky Me! Instant Pancit Canton (Kalamansi)',
      nameTagalog: 'Lucky Me Pancit Canton Kalamansi',
      portionSizeGrams: 80,
      portionDescription: '1 pack (80g)',
      calories: 360,
      proteinG: 8.0,
      carbsG: 50.0,
      fatsG: 14.0,
      confidence: 1.0,
      reasoning: 'Local Barcode Database (Monde Nissin)',
    ),
    '4801981110046': const FoodItem(
      name: 'Lucky Me! Instant Pancit Canton (Chilimansi)',
      nameTagalog: 'Lucky Me Pancit Canton Chilimansi',
      portionSizeGrams: 80,
      portionDescription: '1 pack (80g)',
      calories: 360,
      proteinG: 8.0,
      carbsG: 50.0,
      fatsG: 14.0,
      confidence: 1.0,
      reasoning: 'Local Barcode Database (Monde Nissin)',
    ),
    '4801981110039': const FoodItem(
      name: 'Lucky Me! Instant Pancit Canton (Hot & Spicy)',
      nameTagalog: 'Lucky Me Pancit Canton Hot & Spicy',
      portionSizeGrams: 80,
      portionDescription: '1 pack (80g)',
      calories: 360,
      proteinG: 8.0,
      carbsG: 50.0,
      fatsG: 14.0,
      confidence: 1.0,
      reasoning: 'Local Barcode Database (Monde Nissin)',
    ),
    '4801981110053': const FoodItem(
      name: 'Lucky Me! Instant Pancit Canton (Sweet & Spicy)',
      nameTagalog: 'Lucky Me Pancit Canton Sweet & Spicy',
      portionSizeGrams: 80,
      portionDescription: '1 pack (80g)',
      calories: 360,
      proteinG: 8.0,
      carbsG: 50.0,
      fatsG: 14.0,
      confidence: 1.0,
      reasoning: 'Local Barcode Database (Monde Nissin)',
    ),

    // ═══ CANNED & PANTRY ═══
    '4800110024623': const FoodItem(
      name: 'Century Tuna Flakes in Oil',
      nameTagalog: 'Century Tuna Flakes in Oil',
      portionSizeGrams: 56,
      portionDescription: '1/3 can (56g drained)',
      calories: 110,
      proteinG: 13.0,
      carbsG: 0.0,
      fatsG: 7.0,
      confidence: 1.0,
      reasoning: 'Local Barcode Database (Century Pacific)',
    ),
    '4800110024630': const FoodItem(
      name: 'Century Tuna Flakes Hot & Spicy',
      nameTagalog: 'Century Tuna Hot & Spicy',
      portionSizeGrams: 56,
      portionDescription: '1/3 can (56g drained)',
      calories: 110,
      proteinG: 13.0,
      carbsG: 1.0,
      fatsG: 7.0,
      confidence: 1.0,
      reasoning: 'Local Barcode Database (Century Pacific)',
    ),
    '4800040110014': const FoodItem(
      name: 'San Marino Corned Tuna',
      nameTagalog: 'San Marino Corned Tuna',
      portionSizeGrams: 85,
      portionDescription: '1/2 can (85g)',
      calories: 140,
      proteinG: 12.0,
      carbsG: 2.0,
      fatsG: 9.0,
      confidence: 1.0,
      reasoning: 'Local Barcode Database (CDO Foodsphere)',
    ),

    // ═══ SNACKS & CRACKERS ═══
    '4800194110018': const FoodItem(
      name: 'SkyFlakes Crackers (Original)',
      nameTagalog: 'SkyFlakes Crackers',
      portionSizeGrams: 28,
      portionDescription: '1 single pack (3 crackers, 28g)',
      calories: 120,
      proteinG: 3.0,
      carbsG: 20.0,
      fatsG: 4.0,
      confidence: 1.0,
      reasoning: 'Local Barcode Database (M.Y. San)',
    ),
    '4800047820014': const FoodItem(
      name: 'Piattos Cheese Potato Crisps',
      nameTagalog: 'Piattos Cheese',
      portionSizeGrams: 40,
      portionDescription: '1 small pack (40g)',
      calories: 200,
      proteinG: 2.0,
      carbsG: 26.0,
      fatsG: 10.0,
      confidence: 1.0,
      reasoning: 'Local Barcode Database (Universal Robina)',
    ),
    '4800047820021': const FoodItem(
      name: 'Piattos Sour Cream & Onion Crisps',
      nameTagalog: 'Piattos Sour Cream',
      portionSizeGrams: 40,
      portionDescription: '1 small pack (40g)',
      calories: 200,
      proteinG: 2.0,
      carbsG: 26.0,
      fatsG: 10.0,
      confidence: 1.0,
      reasoning: 'Local Barcode Database (Universal Robina)',
    ),
    '4800047820038': const FoodItem(
      name: 'Nova Country Cheddar Multigrain Snacks',
      nameTagalog: 'Nova Country Cheddar',
      portionSizeGrams: 40,
      portionDescription: '1 small pack (40g)',
      calories: 200,
      proteinG: 2.0,
      carbsG: 27.0,
      fatsG: 9.0,
      confidence: 1.0,
      reasoning: 'Local Barcode Database (Universal Robina)',
    ),

    // ═══ POPULAR GLOBAL BRANDS (Common in PH) ═══
    '3017620422003': const FoodItem(
      name: 'Nutella Hazelnut Spread',
      nameTagalog: 'Nutella',
      portionSizeGrams: 15,
      portionDescription: '1 tbsp (15g)',
      calories: 81,
      proteinG: 1.0,
      carbsG: 8.6,
      fatsG: 4.6,
      confidence: 1.0,
      reasoning: 'Local Barcode Database (Ferrero)',
    ),
    '7622210404015': const FoodItem(
      name: 'Oreo Original Sandwich Cookies',
      nameTagalog: 'Oreo Original',
      portionSizeGrams: 28.5,
      portionDescription: '3 cookies (28.5g)',
      calories: 140,
      proteinG: 1.0,
      carbsG: 20.0,
      fatsG: 6.0,
      confidence: 1.0,
      reasoning: 'Local Barcode Database (Mondelez)',
    ),
    '5449000000996': const FoodItem(
      name: 'Coca-Cola Regular',
      nameTagalog: 'Coke Regular',
      portionSizeGrams: 330,
      portionDescription: '1 can (330ml)',
      calories: 139,
      proteinG: 0.0,
      carbsG: 35.0,
      fatsG: 0.0,
      confidence: 1.0,
      reasoning: 'Local Barcode Database (Coca-Cola)',
    ),
    '5449000000286': const FoodItem(
      name: 'Coca-Cola Zero Sugar',
      nameTagalog: 'Coke Zero',
      portionSizeGrams: 330,
      portionDescription: '1 can (330ml)',
      calories: 1,
      proteinG: 0.0,
      carbsG: 0.0,
      fatsG: 0.0,
      confidence: 1.0,
      reasoning: 'Local Barcode Database (Coca-Cola)',
    ),
  };

  /// Lookup a product by exact barcode string.
  /// Returns null if not present in the curated local list.
  static FoodItem? lookup(String barcode) {
    final clean = barcode.trim();
    if (clean.isEmpty) return null;
    return _products[clean];
  }

  /// Whether the database has this barcode.
  static bool contains(String barcode) => lookup(barcode) != null;
}
